### ISSUE TITLE
Flamethrower (R) icon wrong

### ISSUE THREAD

**Issue by ST-DDT** [DaCyclops/GDIW#11]
Hi,

while playing GDIW with the latest update `v0.14.13` i noticed that the flamethrower (R) recipe icon is wrong. I didn't notice this bug in previous releases.

![flamethrower-ingame](https://cloud.githubusercontent.com/assets/1579362/24322312/8974f84e-1161-11e7-8ced-de70ae2167a6.png)
![flamethrower-tech](https://cloud.githubusercontent.com/assets/1579362/24322314/8e5351da-1161-11e7-9a55-f4fdab364eab.png)
![flamethrower-production](https://cloud.githubusercontent.com/assets/1579362/24322315/919cb278-1161-11e7-986c-4df662bbed9b.png)

**Comment by DaCyclops** [comment]
I have noticed this issue myself, and need to find time to work out why the icon code that is working for every OTHER recipe isn't working for Flamethrower and Sulfur (which are both vanilla, which is odd)....

Crap, I know why now. Bugger. Same problem I had in the first version, which I fixed, and forgot to put back in this version. Yeah, ill get that fixed...

**Comment by DaCyclops** [comment]
Yeah, turns out, I had the code already IN data.lua, but forgot that I had commented it out and wasnt including data.lua.... Im an idiot. Should be fixed in next version.
