### ISSUE TITLE
0.16

### ISSUE THREAD

**Issue by Saylt** [DaCyclops/GDIW#12]
Hi there!

Any chances to update this mod to be compatible with 0.16?

**Comment by ST-DDT** [comment]
AFAICT this mod is (almost) compatible as is. 
* You only have to unpack it
* change the factorio version inside info.json
* add the folloging to data.lua

````lua
data.raw.recipe["sulfur"].icon_size = data.raw.item["sulfur"].icon_size
data.raw.recipe["flamethrower-ammo"].icon_size = data.raw.ammo["flamethrower-ammo"].icon_size
````

* (and repack it).

~~GDIW_0.15.216.zip~~ Unoffical port to Factorio 0.16. (Based on 0.15.2) I use it myself.
EDIT: Use official version.

**Comment by Saylt** [comment]
Great!

Thank you for the information! Well check it ASAP :)

**Comment by DaCyclops** [comment]
Thank you very much @ST-DDT for compensating for my ~~rapmpant lazyness~~ busyness. 

Okay, releasing an official 0.16, which is basically ST-DDTs notes in actual mod form.
