### ISSUE TITLE
Update of Py breaking GDIW 

### ISSUE THREAD

**Issue by DrKilledalot** [DaCyclops/GDIW#18]
updatet Py`s mods today, next startup (besides getting a similar error with creative mode fix) 
iam getting this put out 
![grafik](https://user-images.githubusercontent.com/30718202/38646297-aa6ed5fc-3de7-11e8-8e3d-9fdd75bbdbdb.png)

**Comment by OvermindDL1** [comment]
Same issue.

**Comment by OvermindDL1** [comment]
Although I don't think it's the fault of this mod specifically, but the engine accepts the other mod's broken ingredients so the mod should too...

**Comment by OvermindDL1** [comment]
I seemed to have fixed it locally by adding this at line 71:
```lua
  local ingredients = {}
  for I = 1, #vrn.ingredients do
    if vrn.ingredients[I] then
      table.insert(ingredients, vrn.ingredients[I])
    end
  end
```
And changing the set on line 130 (now 136/137 with the above change) to be this (wrapped it in an `if` check):
```lua
          if rawResults ~= nil then
            if rawResult.icon then
              table.insert(newicons,{icon=rawResult.icon})
            elseif rawResult.icons then
              newicons = util.table.deepcopy(rawResult.icons)
            end
            if #newicons > 0 then break end
          end
```

**Comment by ghost** [comment]
could you post the changes with the surrounding code?, i can't seem to get the fix working

**Comment by DrKilledalot** [comment]
Well from what i understand , this is py`s fault because it specifies less usable slots for a machine then the machine can actully process in some of its recipes (for example crude oil desulfuring with salt) ,
this also causes FNEI to not display these kind of recipes

**Comment by DrKilledalot** [comment]
@Deluxeinator  Well I found that the last endpoint to close the function is missing 
to fix this just write the word   "end" at the bottom of the file

**Comment by OvermindDL1** [comment]
Do you still need a patch for the code changes?  I can make one if needed?  :-)

**Comment by mcdonnellj** [comment]
I'd be very grateful to see a patch up on the mod site!

**Comment by OvermindDL1** [comment]
Here's my fixed one for now, I will not upload it to the portal (nor should anyone else) but it's available here to use.

https://overminddl1.com/Factorio/fixes/GDIW_0.16.2.zip

**Comment by bigyihsuan** [comment]
I've been getting the same issue. Some more info: https://mods.factorio.com/mod/GDIW/discussion/5b36a8271d07c50009e75694

@OvermindDL1 you should make a pull request with the new code.

**Comment by DaCyclops** [comment]
Changes merged in, with adjustments due to updated code.

Should be live in 0.16.3 and 0.17.2
