### ISSUE TITLE
Issue with GDIW (boB+Angel+Py+yuoki)

### ISSUE THREAD

**Issue by AshPrinny** [DaCyclops/GDIW#20]
failure to load
Data-fixes.lua:104: attempt to index local 'b'(a nil value)

Seemingly no clash with other mods (seeing as it asks for only GDIW to be disabled) complete List of mods: 
![factorio gdiw](https://user-images.githubusercontent.com/41396697/42908591-a312524c-8ae1-11e8-86fb-8361fc4872f3.png)
Edit: Had to reupload IMG because of cutoff

**Comment by Firemonkey08** [comment]
I think Py kills it. There is a new mod, which can handle it.

**Comment by ghost** [comment]
> 
> 
> I think Py kills it. There is a new mod, which can handle it.

what is it called, can't seem to find it

**Comment by Unifire1** [comment]
PyCoalTBaA
https://mods.factorio.com/mod/PyCoalTBaA

**Comment by DaCyclops** [comment]
FYI, latest update  should handle whatever was causing this issue from now on.
