### ISSUE TITLE
16.3 is apparently also missing a ingredients nil check

### ISSUE THREAD

**Issue by Dormanil** [DaCyclops/GDIW#22]
I am getting the following error when trying to load GDIW:
![image](https://user-images.githubusercontent.com/6816490/54073427-3fce1780-4287-11e9-85ae-4151b64f960e.png)

This is my current mod list, should it be of any help.
![image2](https://user-images.githubusercontent.com/6816490/54073458-99364680-4287-11e9-811e-a5195bbae780.png)

**Comment by DaCyclops** [comment]
Okay. Ported those changes backwards on the Mod Portal to 0.16.4. 
https://mods.factorio.com/mod/GDIW

No updates in Github - its fully 0.17 now

**Comment by Dormanil** [comment]
Many thanks!

**Comment by Dormanil** [comment]
Actually, seems like you ported those changes only partially, I tried my hand at it, and with this one, I at least get through startup.

https://gist.github.com/Dormanil/268c81125b56e334bff3dea049aaabfd
