### ISSUE TITLE
Incorrect Dependencies/Dependency labeling

### ISSUE THREAD

**Issue by TheYunru** [DaCyclops/GDIW#24]
Attempting to run this mod stand alone results in the following error:
Failed to load mod "GDIW": Mod GDIW dependency (?) angelspetrochem > = 0.0.0 not matching pattern "[?!] ModName [ModVersion specifier]".

**Comment by TheYunru** [comment]
My apologies, may just be a version mismatch. Will confirm either way as soon as done downloading experimental build.

**Comment by DaCyclops** [comment]
It seems like you may have been trying to use the 0.17 version in 0.16 (0.17 added optional dependencies)

**Comment by TheYunru** [comment]
Yep, can confirm that after updating it works perfectly.
