### ISSUE TITLE
bug(angle mod)

### ISSUE THREAD

**Issue by ghost** [DaCyclops/GDIW#25]
![QQ截图20190317012956](https://user-images.githubusercontent.com/26688465/54486467-c1dfc100-48c3-11e9-8a8c-e8f96133d11b.png)

**Comment by DaCyclops** [comment]
Could you confirm what version your using?

**Comment by ghost** [comment]
game version 0.16.51 and GDIW version 0.16.3 and 0.16.4 
0.16.3 and 4 is wrong 
now I use  it 0.16.2 ,It can operate normally.
i add angle mod,
I'm sure it was their conflict.

**Comment by DaCyclops** [comment]
It appears a bit of old code was causing an issue. It was already disabled in the 0.17 version. I am removing it from both. Expect updated versions soon.
