### ISSUE TITLE
0.14.10 error on loading

### ISSUE THREAD

**Issue by Saylt** [DaCyclops/GDIW#8]
Once the game starts, it loads the mods. Once the queue comes to the GDIW, game crashes with the following error:
`gdiw/data-final-fixes.lua:90:attempt to get length of field 'results' (a nil value)`
[https://i.imgur.com/ihf6dL1.png](https://i.imgur.com/ihf6dL1.png)

**Comment by DaCyclops** [comment]
Could you give me your modlist so I can doublecheck?

**Comment by DaCyclops** [comment]
Actually, from the last time I tested it, it appears someone added a recipe that has two inputs, no icon, and a fluid output. so my code was trying to find a fluid in the items list.... 
**sigh**

incoming 0.14.11.

**Comment by Saylt** [comment]
Thanks for the fix!
